### ISSUE TITLE
Sometimes Hilton doesn't show up. It happened to me and to Garry_Moonlover

### ISSUE THREAD

**Issue by kvakes** [windingtree/stays#110]
![Screenshot from 2022-04-14 09-07-59](https://user-images.githubusercontent.com/377005/163332662-21ff2511-f6ab-4d28-aaea-4e29bcd3e6cb.png)

**Comment by valera-rozuvan** [comment]
Could not reproduce.

**Comment by AntNezh** [comment]
Could not reproduce. May be was fixed

**Comment by valera-rozuvan** [comment]
Closing this.
