### ISSUE TITLE
bug: check-in flow shows incorrect date range

### ISSUE THREAD

**Issue by mfw78** [windingtree/stays#169]
**Report**

> Hey guys, I'm at the Front Office from Hilton and I'm scanning a QR code from a random booking with my mobile MetaMask, but when scan it nothing shows up (I'm connected to the Gnosis chain). Is that correct?
> Cause the same happened with an actual guest this morning.
> Also Token 9 is booked for 17-24 April. but when the guest showed up he showed token 9 with 18-25 April (according to the Front Office).

**Comment by mfw78** [comment]
**NOTE:** `tokenId` index starts at **1** for OpenZeppelin ERC-721 implementation.

Initial triage shows `tokenURI` for token index 9 of:

```json
{
  "name": "Stay Amsterdam #9",
  "description": "Stay at lodging facility",
  "image": "https://bafybeiakjrhbgmv54l4nsdwxxcdfkpeqh33m45asmw6rkwhujryw2qa7n4.ipfs.dweb.link/token.png",
  "external_url": "https://win.so/tokens?tokenId=9",
  "attributes": [
    {
      "trait_type": "facilityId",
      "value": "0xC1BDBD052074D8688F71D94BF3E666A3F2DFF8D4994E78197215899778FB192C"
    },
    {
      "trait_type": "spaceId",
      "value": "0x859ADCA4C418A6D91EF99E63B07C21F5CC1D2036A08CBAD18A32F5F78A9B4C95"
    },
    {
      "trait_type": "startDay",
      "value": "54"
    },
    {
      "trait_type": "numberOfDays",
      "value": "7"
    },
    {
      "trait_type": "quantity",
      "value": "2"
    }
  ]
}
```

**Comment by AntNezh** [comment]
The bug is reproduced, please fix it
![unknown](https://user-images.githubusercontent.com/103627480/163996072-74106fc7-33ee-4fbf-a74b-699d465bc612.png)

**Comment by mfw78** [comment]
This seems to be a timezone issue. Therefore, I'd suggest that we record the facility's timezone, and that all stays as they are tied to a facility inherit the timezone as such.

**Comment by kostysh** [comment]
This issue affects both the smart contract and the Dapp and can be solved also from both sides.
I propose to solve it in the following steps:
1) set `zeroDate` to the start of the day (as GMT value)
2) add time zone information to the facility struct in the smart contract (different facilities can have different time zone settings)
3) on the smart contract and frontend sides we can use the facility's time zone for the calculation of the check-in and check-out dates

**Comment by AntNezh** [comment]
I notice some else. When I do a search for the first time after loading page all dates are correctly. But when after the first search I change the dates and search ones more the bug of offset by 1 day is reproduced .
