### ISSUE TITLE
Country dropdown within facility adding/management is not working

### ISSUE THREAD

**Issue by kvakes** [windingtree/stays#72]
OS: Ubuntu 20.04
Browser: Firefox 99

![Screenshot from 2022-04-12 19-31-24](https://user-images.githubusercontent.com/377005/163020437-15fc0573-1c04-40df-b542-3544e67f5497.png)

**Comment by bobetbat** [comment]
Could not reproduce, works for me.
OS: MacOS 12.01
Browser: Firefox 99

**Comment by bobetbat** [comment]
works for me.
OS: MacOS 12.01
Browser: Firefox 99

**Comment by valera-rozuvan** [comment]
~~Could not reproduce.~~

**Comment by AntNezh** [comment]
OS: Windows 10 Pro
Browser: Firefox 99

https://user-images.githubusercontent.com/103627480/163989794-9e527a29-aa5e-4c31-b5fb-cf92d5937695.mp4

**Comment by AntNezh** [comment]
Fixed
