### ISSUE TITLE
Uploading facility images is not working

### ISSUE THREAD

**Issue by kvakes** [windingtree/stays#73]
I was able to upload facility logo, but then while trying to upload multiple "facility images" (they are called "room images" for some reason on the facility page), I get this error:

`FacilityProfileCard: Error: Cannot connect to the source: https://api.web3.storage/upload`

**Comment by valera-rozuvan** [comment]
Will try to reproduce, and fix if still an issue.

**Comment by valera-rozuvan** [comment]
Could not reproduce.

**Comment by AntNezh** [comment]
Could not reproduce.

**Comment by valera-rozuvan** [comment]
Closing this.
