### ISSUE TITLE
Can't book room even if I have enough DAI in the account

### ISSUE THREAD

**Issue by kvakes** [windingtree/stays#77]
![Screenshot from 2022-04-12 22-59-30](https://user-images.githubusercontent.com/377005/163055378-618307d1-7201-42b7-9438-8705afe1b429.png)
![Screenshot from 2022-04-12 22-58-42](https://user-images.githubusercontent.com/377005/163055382-0c8ab735-868f-452c-a662-0fd95762e236.png)

**Comment by mfw78** [comment]
What's the steps to reproduce this? Is it just "Book with DAI" ?

**Comment by kvakes** [comment]
Fixed in https://github.com/windingtree/stays/pull/82
