### ISSUE TITLE
QR code issues

### ISSUE THREAD

**Issue by kvakes** [windingtree/stays#85]
1) Remove hotel description from the QR code display
2) Change "guests" to "rooms" in the view (I booked my token for 5 nights)

![Screenshot from 2022-04-13 09-45-13](https://user-images.githubusercontent.com/377005/163126207-cf18d54f-e70a-4479-9b70-557fd3371800.png)
![Screenshot from 2022-04-13 09-45-01](https://user-images.githubusercontent.com/377005/163126210-76c2ccc0-2b34-43cb-bd2b-28139b8acfb5.png)

**Comment by bobetbat** [comment]
https://github.com/windingtree/stays/pull/90

**Comment by bobetbat** [comment]
https://github.com/windingtree/stays/pull/90
