### ISSUE TITLE
Feature: Rates and Rate Modifiers

### ISSUE THREAD

**Issue by kvakes** [windingtree/stays#91]
Right now I can only say that my Space has a certain price, e.g. 100 xDAI. This rate will be available indefinitely, the only way for me to limit it is to remove the space. Instead I propose to introduce the concept of "Rate", so our internal hierarchy will look like this:

`Facility - Space - Rate - Modifier`

Facility ~ Hotel
Space ~ Room Type
Rate ~ Room Rate
Modifier ~ Logical/Mathematical rules that change the Room Rate

## Rate Properties

- Price in xDAI
- Date Range: date range FROM and TO (with the possibility to specify that the rate should be valid until 1/2/3 years from TODAY)
- Minimum Stay: minimum number of nights required for this rate to trigger
- Rate Modifiers that should apply to this rate

### Example: Queen Room

Rate 1:
- 150 xDAI
- Available from April 17 to 25
- Minimum Stay: 1 night
- Rate modifiers: none

Rate 2:
- 130 xDAI
- Available from April 17 to 25
- Minimum stay: 8 nights
- Rate modifiers: none

## Rate Modifiers

Rate modifiers are stored in a separate pool of available rate modifiers. They don't belong to a Space, i.e. different Spaces may use the same Rate Modifier.

0) Blackout: specify dates during which the rate is not available
1) Weekend price increase: automatically increase the rate by a certain amount of xDAI or by %.
2) Holiday price increase: specify holiday dates (in your country) and increase the price by xDAI amount or by %
3) High season, low season modifiers: specify a date range during which prices go up or down by xDAI amount or by %
4) Loyalty: you may specify that a holder of a certain number of tokens / NFT will get a discount (xDAI amount or %)

**Comment by mcchagas** [comment]
Kostia will analize this feature to provide the specification and initial tasks. Target 04Apr22.

**Comment by xdaluca** [comment]
referred to in windingtree/win#22
